language: node_js

before_install:
- npm install

cache: npm

before_deploy:
  - npm install firebase-tools -g
 - cd functions && npm install
 - cd ..

deploy:
 provider: firebase
 token:
  secure: "WxgWfFR4Hvsi25CCIoxFGoIL+qWaqrms1Y0wc/or9mM0yTQIho7pkkXYPEWKGkMEkn12VwvkjvgJ0u3aP/BTVhI8hLPapeFwGEiIUiOuO63De0t+04ZIeGtYpxF7WKp8vbarAgDgBEV7Q2m5au59MJgMXjwEEKMWuCaTXuxsH9ttIC/CwOJ80pxAN9T1jcannTGlZgdSl2NM71DJoQb6XtCNVACyLCDVpcIYhIqgV+O8GqrboYH67pOccyOkOVWZC8egXEM80eATIUrIOqjwgn2FLQGuWQhXLXnF19AdGDCOvE29ur0l7bzwi7EcKK86kVSFngaiLKznXZpcPXGXFRcxc8KR645+n7if/kftBCW+Koj2XeJ1uKVKBdETP977soXidqrQ98tBe8hly1w3orq6HxEmbk6iyEFeAl9B+UKybXUmvLcVuAzahJQef08fr7NMwEPvM3geV4oYz1s8wLvB4I4Uk5BJih/KeMeu8a4zEGLkpEJ6aKPE4nqXM+p/KS6d6Tu146SGNEoSACX8zYpcVHFQZKz7PoHFrwSnJ38RfrObQ6VRIMLs+xtHlzKIFMuQbi5QdoGEBpLxNzTypfiqCdOzopI5CAhrE3vR0YZXFpA9fHTrav6YdZK6/xCOUU5C4yQv6Q4J3wTjNERc3Wp6PaltTCb9t9Nb2/hxHiU="
 skip_cleanup: true
